#!/usr/bin/with-contenv bash

### Set Defaults
  tokensFromEnv="LDAP_HOST LDAP_BIND_DN LDAP_BIND_PW LDAP_BASE_DN LDAP_ATTRIBUTE LDAP_SCOPE LDAP_FILTER LDAP_GROUP_ATTRIBUTE"

  AUTHENTICATION_TYPE=${AUTHENTICATION_TYPE:-NONE}
  MAINTENANCE=${MAINTENANCE:-"FALSE"}
  PHP_TIMEOUT=${PHP_TIMEOUT:-"180"}
  UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE:-"2G"}
  STAGE=${STAGE:-"DEVELOP"}
  LDAP_ATTRIBUTE=${LDAP_ATTRIBUTE:="uid"}
  LDAP_SCOPE=${LDAP_SCOPE:="sub"}
  LDAP_FILTER=${LDAP_FILTER:="(objectClass=person)"}
  LDAP_GROUP_ATTRIBUTE=${LDAP_GROUP_ATTRIBUTE:="uniquemember"}
  LLNG_HANDLER_HOST=${LLNG_HANDLER_HOST="llng-handler"}
  LLNG_HANDLER_PORT=${LLNG_HANDLER_PORT="2884"}
  WEB_USER=${WEB_USER:-admin}
  WEB_PASS=${WEB_PASS:-password}
  
### Map Authentication
  case "$AUTHENTICATION_TYPE" in
      "BASIC")
      htpasswd -b -c /etc/nginx/htpasswd $WEB_USER $WEB_PASS
      sed -i "/ location \//a\ \ \  auth_basic "Protected"; auth_basic_user_file /etc/nginx/htpasswd;" /etc/nginx/conf.d/02-default.conf
      echo '** [nginx-php-fpm] Setting Basic Authentication'
      ;;
      "LLNG")
      if [ -f "/etc/nginx/conf.d/02-default.llng" ]; then
        sed -i "s/<LLNG_HANDLER_HOST>/$LLNG_HANDLER_HOST/g" /etc/nginx/conf.d/02-default.llng
        sed -i "s/<LLNG_HANDLER_PORT>/$LLNG_HANDLER_PORT/g" /etc/nginx/conf.d/02-default.llng
        echo '** [nginx-php-fpm] Setting LLNG Authentication'
        mv /etc/nginx/conf.d/02-default.conf /etc/nginx/conf.d/02-default.orig
        mv /etc/nginx/conf.d/02-default.llng /etc/nginx/conf.d/02-default.conf
      else
        echo '** [nginx-php-fpm] ERROR: Cannot find specific Configuration for LLNG Authentication exiting.'
        exit 1
      fi
      ;;
      "NONE")
      echo '** [nginx-php-fpm] Relying on Application Authentication'
      ;;
     *)
      echo '** [nginx-php-fpm] Unknown AUTHENTICATION_TYPE option. Relying on Application Authentication'
     ;;
  esac


### Adjust NGINX Runtime Variables
  
  sed -i -e "s/<UPLOAD_MAX_SIZE>/$UPLOAD_MAX_SIZE/g" /etc/nginx/nginx.conf
  sed -i -e "s/<PHP_TIMEOUT>/$PHP_TIMEOUT/g" /etc/nginx/conf.d/02-default.conf

  if [ "$MAINTENANCE" = "TRUE" ] || [ "$MAINTENANCE" = "true" ];  then
    echo '** MAINTENANCE MODE ACTIVATED - THIS IMAGE WILL NOT SERVE PAGES'
    mv /etc/nginx/conf.d/02-default.conf /etc/nginx/conf.d/02-default.conf.orig
    mv /etc/nginx/conf.d/01-ldap.conf /etc/nginx/conf.d/01-ldap.conf.orig
    mv /etc/nginx/conf.d/maintenance.conf.maint /etc/nginx.conf.d/maintenance.conf
  fi

### LDAP Setup
  for envVar in $tokensFromEnv; do
    envValue=$(echo "${!envVar}" | sed -e 's/[&\\\$]/\\&/g')
	sed -i -e "s|\$${envVar}|${envValue}|g" /etc/nginx/conf.d/01-ldap.conf;
  done

mkdir -p /www/logs/nginx
chown -R nginx /www/logs/nginx
mkdir -p /tmp/nginx
chown -R nginx /tmp/nginx

mkdir -p /tmp/state 
touch /tmp/state/09-nginx

