#!/usr/bin/with-contenv bash


if [ ! -f /tmp/state/10-nginx ]; then
sleep 2
	
	tokensFromEnv="LDAP_HOST LDAP_BIND_DN LDAP_BIND_PW LDAP_BASE_DN LDAP_ATTRIBUTE LDAP_SCOPE LDAP_FILTER LDAP_GROUP_ATTRIBUTE"

	LDAP_ATTRIBUTE=${LDAP_ATTRIBUTE:="uid"}
	LDAP_SCOPE=${LDAP_SCOPE:="sub"}
	LDAP_FILTER=${LDAP_FILTER:="(objectClass=person)"}
	LDAP_GROUP_ATTRIBUTE=${LDAP_GROUP_ATTRIBUTE:="uniquemember"}

	for envVar in $tokensFromEnv; do
	  envValue=$(echo "${!envVar}" | sed -e 's/[&\\\$]/\\&/g')
	  sed -i -e "s|\$${envVar}|${envValue}|g" /etc/nginx/conf.d/01-ldap.conf;
	done

	### Force Reset Permissions for Security
	chown -R nginx:www-data /www/html

        mkdir -p /www/logs/nginx
    	mkdir -p /tmp/nginx
        chown -R nginx /www/logs/nginx
        chown nginx /tmp/nginx
        mkdir -p /tmp/state
	echo 'Initialization Complete' >/tmp/state/10-nginx
fi

echo ''
echo '** Starting nginx..'
exec nginx
